FROM postgres:16-bookworm

USER root
RUN apt update && apt install -y --no-install-recommends \
	python3 \
	python3-pip \
	python3-venv
RUN pip install --break-system-packages 'patroni[etcd3,kubernetes,psycopg3]' \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
USER postgres
ENTRYPOINT ["patroni", "/etc/patroni.yaml"]
